--- 
- hosts: all
  become: yes
  tasks:
          #- name: Install Apache
          #  yum: name=apache state=latest
  - name: Install Httpd
    yum: name=httpd state=latest
  
  - name: Copy template
    template:
      src: /home/ec2-user/index.html
      dest: /var/www/html/index.html
      mode: 0777
  - name: Enable Httpd
    shell: |
      systemctl enable httpd
      systemctl start httpd
